rootUrl: 'https://wadeozuqlh.localtunnel.me'
compositeImage: true             # fix "The region bottom bound is outside of the viewport height"
screenshotMode: 'fullpage'
screenshotsDir: './gemini/screenshot'
sessionsPerBrowser: 3

system:
  # exclude:
  #   - 'gemini/gemini-reports/**'
  #   - 'node_modules/**'
  plugins:
    browserstack: {}
    # sauce: {}
    'html-reporter':
      enabled: true
      path: 'gemini/report'
      baseHost: 'http://localhost:3000'
    # 'ssh-tunneler/gemini': 
    #   host: 'http://localhost'
    #   user: 'user'
    #   ports: 
    #     min: 3000
    #     max: 4000
    #   localport: 3000
    #   enabled: true
    #   retries: 3
    #   protocol: 'https'
      # hostname from the original rootUrl 
      # urlDecorator: (baseHost) => { return /^m\./.test(baseHost) ? 'm.remote_host_address': 'remote_host_address'}
 
browsers:
  ie9:
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '9'
 
  ie10:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '10'
 
  ie11:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'internet explorer'
      version: '11'
 
  chrome26_sm:
    windowSize: 400x1024
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '26'

  chrome26_md:
    windowSize: 768x1024
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '26'

  chrome26_lg:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '26'

  chrome19_lg:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'chrome'
      version: '19'

  firefox4:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'firefox'
      version: '4'

  firefox56:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'OS X'
      os_version: '10.12'
      browserName: 'firefox'
      version: '56'

  safari7:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'OS X 10.9'
      # os_version: '10.9'
      browserName: 'safari'
      version: '7'

  safari6:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'OS X'
      os_version: '10.7'
      browserName: 'safari'
      version: '6'

  opera33:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'opera'
      version: '33'
      operaOptions: 
        binary: '/usr/bin/opera'

  opera15:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'opera'
      version: '15'

  opera12:
    windowSize: 1200x900
    desiredCapabilities:
      os: 'WINDOWS'
      os_version: '7'
      browserName: 'opera'
      version: '12.16'

sets:
  desktop:
    files:
      - 'gemini/tests/desktop'
    browsers:
      - firefox4
      - chrome26_lg
      # - chrome19_lg
      - ie9
      # - safari6
      # - opera12
      # - opera15
