version: '2'
services:
  web:
    image: cmcdev/web
    ports:
      - 8000:8000
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/www/web/
    working_dir: /www/web
    command: sh
    # entrypoint: sh /www/docker-start.sh
    container_name: web
    stdin_open: true
    tty: true